import bases

class ScreenManager:
    def __init__(self):
        self.screens: 'list[bases.Screen]' = []
        self.current_screen: 'bases.Screen' = None
        self.running: bool = False

    def add(self, screen: 'bases.Screen'): ...
    def remove(self, screen: 'bases.Screen'): ...
    def change_to(self, screen_name: str): ...
    def start(self, index: int): ...
    def mainloop(self): ...
    def stop(self) -> None: ...
