import pygame as pg
import bases

class Timer:
    def __init__(self, fps: int): 
        self.fps = fps
        self.clock: 'list[Clock]' = []
        self.clock_once: 'list[Clock]' = []
        self.clock_ever: 'list[Clock]' = []

    def add_clock(self, time: int, func: 'function'): ...
    def add_clock_once(self, time: int, func: 'function'): ...
    def add_clock_ever(self, func: 'function'): ...
    def remove_clock(self, time: int, func: 'function'): ...
    def remove_clock_once(self, time: int, func: 'function'): ...
    def remove_clock_ever(self, func: 'function'): ...
    def update(self): ...
    def get_fps(self): ...



class Clock:
    def __init__(self, time: int):
        self.time = time
        self.last_time = 0
        self.funcs = bases.CleanGroup('ClockGroups')

    def add_function(self, func: 'function'): ...
    def remove_function(self, func: 'function'): ...
    def check(self): ...
    def notify(self): ...
    def get_time(self) -> int: ...
    def get_funcs(self) -> 'function': ...
