
import bases

class ScreenInterface:
    def __init__(self, name: str): ...
    def add(self, obj: 'bases.Object'): ...
    def remove(self, obj: 'bases.Object'): ...
    def setup(self) -> None: ...
    def get_nome(self) -> str: ...
    def get_objects(self) -> 'bases.Group': ...